### ISSUE TITLE
怎么确定该使用Restful方式还是RBAC方式？

### ISSUE THREAD

**Issue by zwl1619** [taigacute/leaseapp#2]
怎么确定该使用Restful方式还是RBAC方式？

https://casbin.org/docs/zh-CN/supported-models
![image](https://user-images.githubusercontent.com/13177997/49596130-92f8ab80-f9b4-11e8-901c-83b01d50cb17.png)

如上图所示，Restful这种方式好像没有用到角色，但是您代码中是有角色的，那选择使用restful和rbac方式的依据是什么呢？

**Comment by hsluoyz** [comment]
@zwl1619 in Casbin, RESTful means ``obj`` is URL path, and ``act`` is HTTP method like ``GET``, ``POST``, etc. RBAC means ``sub`` can have roles. So we can see RESTful and RBAC are totally orthogonal. You can use RESTful or RBAC only, or both. It depends on what authorization feature you need to use.

**Comment by glepnir** [comment]
@hsluoyz  nice work。

**Comment by glepnir** [comment]
@zwl1619  不知道为什么 没提示我有issue，才看到。 2者都是可以使用的，RBAC是可以有继承的，这个只是demo。最近在做一个后台的cli 工具。到时候发出来你可以看看。

**Comment by glepnir** [comment]
i will close  this issue
