### ISSUE TITLE
请问初始账号怎么添加？？

### ISSUE THREAD

**Issue by CxcPDF** [taigacute/leaseapp#4]

**Comment by glepnir** [comment]
@CxcPDF  没留这个后门，因为只是个初期结合casbin jwt的demo。 路由那里把 添加的路由 从中间件验证拿出来再添加就可以了

**Comment by CxcPDF** [comment]
authrequired.POST("/addemp", apis.AddEmployee)
authrequired.POST("/addrole", apis.AddCasbin)

请问是这两个语句吗？？

**Comment by CxcPDF** [comment]
> @CxcPDF 没留这个后门，因为只是个初期结合casbin jwt的demo。 路由那里把 添加的路由 从中间件验证拿出来再添加就可以了

authrequired.POST("/addemp", apis.AddEmployee)
authrequired.POST("/addrole", apis.AddCasbin)

请问是这两个语句吗？？

**Comment by glepnir** [comment]
注释掉这2个中间件。就可以访问下面的路由了。不然访问都会要通过中间件进行验证。
```
authrequired.Use(jwt.JWTAuth())
authrequired.Use(authz.AuthCheckRole())
```

**Comment by CxcPDF** [comment]
> 注释掉这2个中间件。就可以访问下面的路由了。不然访问都会要通过中间件进行验证。
> 
> ```
> authrequired.Use(jwt.JWTAuth())
> authrequired.Use(authz.AuthCheckRole())
> ```

非常感谢！！！  这个困扰了我半天

**Comment by glepnir** [comment]
Close
